name: Print Pull Request Context(name of workflow(pipeline))
on:
  workflow_dispatch:
  pull_request:
      types: [opened, edited, reopened]
jobs:
  name-of-single-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context(name of first steps)
        run: echo '${{ toJSON(github.event) }}'