name: Print Pull Request Context(name of workflow(pipeline))
on: workflow_dispatch
jobs:
  name-of-single-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Context(name of first steps)
        run: echo '${{ toJSON(github) }}'