name: Playwright Tests
on:
  push:
    branches: [ main, master ]
jobs:
  job:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Upload some files
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: any step
        run: echo Second job "test2" was fasster
      - name: any step 2
        run: echo Second job "test2" was fasster
